# This is a basic workflow to help you get started with Actions

name: Deployment-Test

# Controls when the workflow will run
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare KinD
        run: echo "preparing KinD"

  deploy-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [prepare-cluster]
    steps:
      - name: Run deployment tests
        run: echo "Running deployment tests"

  deploy-test-azure:
    runs-on: ubuntu-latest  
    needs: [prepare-cluster]
    steps:
      - name: Run deployment tests azure
        run: echo "Running deployment tests"
  
  deploy-test-inmem:
    runs-on: ubuntu-latest  
    needs: [prepare-cluster]
    steps:
      - name: Run deployment tests inmem
        run: echo "Running deployment tests"
