# This is a basic workflow to help you get started with Actions

name: Publish-Artefacts

# Controls when the workflow will run
on:
  workflow_run:
      workflows: [ "Test-All" ]
      types:
        - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to MavenCentral
        run: echo "Publish all artefacts"

  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to DockerHub
        run: echo "Publish all artefacts"
