# This is a basic workflow to help you get started with Actions

name: Unit-Tests

# Controls when the workflow will run
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkstyle
        run: echo "running checkstyle"
      - name: Run markdown lint
        run: echo "running markdown lint"  

  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run unit tests
        run: echo "Running unit tests"
